sudo: required
language: c
compiler:
  - gcc
  - clang
services:
  - docker
before_install:
  - docker pull linuxmaniac/pkg-kamailio-docker:stretch
script: docker run -v $TRAVIS_BUILD_DIR:/code:rw linuxmaniac/pkg-kamailio-docker:stretch /bin/bash -c "export CC=$CC; cd /code; ./test/travis/build_travis.sh"
branches:
  only:
    - 'master'
    - '/^4\.[0-9]+$/'
    - '/^lazedo\.*$/'
notifications:
  email:
    recipients:
      - luis@2600hz.com
    on_success: never
    on_failure: always
